config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "information" => "static_pages#information"
  namespace :ecdsa do
    get "generate_key" => "ecdsa#generate_key"
    get "generate_signature" => "ecdsa#generate_signature"
    get "verify_signature" => "ecdsa#verify_signature"
  end

  namespace :api do
    get "select_d" => "generate_key#select_d"
    get "compute_q" => "generate_key#compute_q"
    get "save_private_key" => "generate_key#save_private_key"
    get "save_public_key" => "generate_key#save_public_key"

    post "gs_upload_message" => "generate_signature#upload_message"
    post "gs_upload_private_key" => "generate_signature#upload_private_key"
    get "gs_check_input" => "generate_signature#check_input"
    
    get "gs_select_k" => "generate_signature#select_k"
    get "gs_compute_kg" => "generate_signature#compute_kg"
    get "gs_compute_r" => "generate_signature#compute_r"
    get "gs_compute_inverse_k" => "generate_signature#compute_inverse_k"
    get "gs_hash_message" => "generate_signature#hash_message"
    get "gs_compute_s" => "generate_signature#compute_s"
    get "save_signature" => "generate_signature#save_signature"

    post "vs_upload_message" => "verify_signature#upload_message"
    post "vs_upload_signature" => "verify_signature#upload_signature"
    post "vs_upload_public_key" => "verify_signature#upload_public_key"
    get "vs_check_input" => "verify_signature#check_input"

    get "vs_boolean1" => "verify_signature#boolean1"
    get "vs_hash_message" => "verify_signature#hash_message"
    get "vs_compute_w" => "verify_signature#compute_w"
    get "vs_compute_u1" => "verify_signature#compute_u1"
    get "vs_compute_u2" => "verify_signature#compute_u2"
    get "vs_compute_x" => "verify_signature#compute_x"
    get "vs_compute_v" => "verify_signature#compute_v"
    get "vs_vsrify_signature" => "verify_signature#verify_signature"

    get "get_elliptic_curve_params" => "elliptic_curve#get_elliptic_curve_params"
    get "download_key" => "download#download_key"
    get "download_signature" => "download#download_signature"
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      Thuật toán chữ ký số trên đường cong elliptic
    </small>
    <small class="pull-right">
      <ul>
        <li><%= link_to "Thông tin", information_path %></li>
      </ul>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag(image_path("icon.png"), alt: "error", id: "logo"), root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Trang Chủ", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Chữ ký số ECDSA <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sinh khóa", ecdsa_generate_key_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sinh chữ ký", ecdsa_generate_signature_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Xác minh chữ ký", ecdsa_verify_signature_path %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECDSA</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
  <%= javascript_include_tag "application", "data-turbolinks-track": true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= render "layouts/flash" %>
    <%= yield %>
  </div>
  <%#= render "layouts/footer" %>
</body>
</html>